# Generated by Django 3.0.7 on 2020-07-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('Title', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('lang', models.CharField(max_length=10)),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
